"""main.py's flow, re-expressed on the MAF graph workflow API (WorkflowBuilder).

============================================================================
DISCLAIMER: THIS FILE WAS GENERATED BY CLAUDE (at the user's explicit request).
It is a learning companion to main.py — the imperative original is left
untouched. Read it critically; don't treat it as your own hand-written work.
Run it the same way as main.py (from inside project/):  uv run workflow_graph.py
============================================================================

Design rationale (why this shape, not a "pure" cycle of agent-nodes):
  Every AgentExecutor owns its OWN session (agent_framework/_workflows/
  _agent_executor.py:177). That makes a multi-turn *conversation* awkward to model
  as a cycle of agent-nodes: two nodes can't share one growing history without
  threading `full_conversation` down every edge and re-feeding it each turn. So
  the interactive front half lives inside ONE custom executor (GatherRequirements)
  that owns the dev session and loops via request_info; the deterministic back
  half (write -> code -> review -> fix) is where real agent-nodes + conditional
  edges + the iteration cap actually pay off. This mirrors the conclusion reached
  for the imperative version: graphs are worst at dynamic, human-driven control
  flow, best at deterministic orchestration.

Two wins this gives us over main.py for free:
  1. No session pollution. main.py shares ONE session between Soham and the Judge,
     so the Judge's verdicts leak into Soham's history. Here the Judge runs
     STATELESS on its own transcript (see GatherRequirements), and every
     AgentExecutor node has its own isolated session.
  2. Bounded loops. WorkflowBuilder(max_iterations=...) caps total supersteps
     (DEFAULT_MAX_ITERATIONS = 100), so the XL<->Amma review loop can't ping-pong
     forever the way main.py's `while True` can. (Caveat: it bounds the WHOLE run,
     front half included — see build_workflow().)
"""

import asyncio
from dataclasses import dataclass
from pathlib import Path

from agent_framework import (
    AgentExecutor,
    AgentExecutorRequest,
    AgentExecutorResponse,
    Case,
    Default,
    Executor,
    Message,
    WorkflowBuilder,
    WorkflowContext,
    executor,
    handler,
    response_handler,
)
from agents import amma_agent, judge_agent, sm_agent, xl_agent
from constants import OUTPUTS_DIR
from models import ProjectDetails
from tools import write_to_file


# The payload we hand the driver whenever we need a human turn. `kind` lets the
# ONE response_handler below tell a requirements answer apart from a yes/no
# confirmation; `text` is what the driver prints before reading input.
@dataclass
class UserPrompt:
    text: str
    kind: str  # "requirements" | "confirm"


# ---------------------------------------------------------------------------
# Front half: interactive requirements gathering (human-in-the-loop)
# ---------------------------------------------------------------------------
class GatherRequirements(Executor):
    """Owns the Soham<->user<->Judge loop, then emits a ProjectDetails downstream.

    NOTE — request_info in the GRAPH API does NOT return inline. Calling
    `await ctx.request_info(...)` only SUSPENDS the run; the human's answer is
    delivered to a separate @response_handler (paired by request/response types).
    That is why this reads as a small state machine (`run` kicks it off, the
    response_handler is the loop body) instead of a straight-line `while`.
    """

    def __init__(self, dev_agent, judge, dev_session, id: str = "gather"):
        super().__init__(id=id)
        self._dev = dev_agent
        self._judge = judge
        # Claude: ONE source of truth — the shared dev session. Soham AND the judge
        # both run on it, so every user turn lands in the session as a side effect,
        # exactly like main.py (the judge run is what injects the user's message).
        # Accepted tradeoff, same as main.py: the judge's verdicts pollute Soham's
        # history and the judge re-reads its own past verdicts. The proposal and the
        # PresentProposal announce later read this same, complete session.
        self._session = dev_session

    @handler
    async def run(self, _trigger: str, ctx: WorkflowContext[ProjectDetails]) -> None:
        # System messages stay developer-controlled (never interpolate user input):
        # https://learn.microsoft.com/en-us/agent-framework/agents/safety#keep-system-messages-developer-controlled
        greeting = await self._dev.run(
            Message(
                role="system",
                contents=["Greet the user, and ask him his requirements."],
            ),
            session=self._session,
        )
        await ctx.request_info(UserPrompt(greeting.text, "requirements"), str)

    @response_handler
    async def on_human_turn(
        self, request: UserPrompt, response: str, ctx: WorkflowContext[ProjectDetails]
    ) -> None:
        if request.kind == "confirm":
            if response.strip().lower() == "y":
                # Proposal generated from the shared session, which by now holds the
                # full conversation — the judge below runs on the session too, so
                # every user turn (including the one that flips `ready`) is already
                # in it. Same prompt as main.py.
                details = await self._dev.run(
                    Message(
                        role="system",
                        contents=[
                            "Generate a project name and a proposal based on your "
                            "discussion. The project name should be in snake_case. "
                            "The proposal contents should be in markdown format."
                        ],
                    ),
                    session=self._session,
                    options={"response_format": ProjectDetails},
                )
                await ctx.send_message(details.value)  # -> write_proposal
                return
            # Improvement over main.py (which discarded a non-"y" answer — its TODO
            # asked for exactly this): treat it as more requirements input below.

        # Requirements turn (or a "no, here's more" confirm answer): run the judge
        # ON THE SESSION so `response` is injected into the shared history (this is
        # how main.py gets every user turn into the session), then either ask again
        # or move to confirmation.
        #
        # Claude NOTE — the EARLIER BUGGY version is kept commented just below as a
        # lesson. It ran the judge STATELESS on a separate `self._transcript`, so user
        # turns were never written into the dev session; and on the turn the judge
        # flipped to `ready` we skipped dev.run(response) too, so that message reached
        # neither. Proposal-gen then ran on a session holding only the greeting and
        # "restated the greeting" (see the requirements_intake_assistant output, whose
        # line 1 was literally the greeting). Running the judge ON the session fixes it.
        #     self._transcript.append(Message(role="user", contents=[response]))
        #     verdict = await self._judge.run(self._transcript)  # stateless: no session=
        verdict = await self._judge.run(response, session=self._session)
        ready = bool(verdict.value and verdict.value.ready)

        if ready:
            await ctx.request_info(
                UserPrompt(
                    "Looks like we have everything we need. Should we proceed "
                    "with the final proposal? (y/n)",
                    "confirm",
                ),
                str,
            )
            return

        reply = await self._dev.run(response, session=self._session)
        await ctx.request_info(UserPrompt(reply.text, "requirements"), str)


# ---------------------------------------------------------------------------
# Back half: deterministic transforms + real agent nodes
# ---------------------------------------------------------------------------
@executor(id="write_proposal")
async def write_proposal(
    details: ProjectDetails, ctx: WorkflowContext[AgentExecutorRequest]
) -> None:
    # We write proposal.md ourselves (deterministic) instead of letting an agent
    # do it — same reasoning as main.py. write_to_file is a @tool but stays
    # directly callable.
    project_path = OUTPUTS_DIR / details.project_name
    proposal_file_path = write_to_file(
        filename="proposal.md", contents=details.proposal, filepath=project_path
    )
    # Stash the dynamic paths in the SHARED workflow state (one State per run) so
    # the review / fix / finalize steps downstream can read them.
    ctx.set_state("project_path", str(project_path))
    ctx.set_state("proposal_file_path", str(proposal_file_path))

    await ctx.send_message(
        AgentExecutorRequest(
            messages=[
                Message(
                    role="system",
                    contents=[
                        f"Read the contents of this proposal: {proposal_file_path} "
                        f"and code a working solution at {project_path / 'out'} "
                        "directory. IMPORTANT: All project related files (source "
                        "code, readme etc.) should be mandatorily inside the 'out' "
                        "directory. Once you are done coding, inform the user and "
                        "give him the path where your code is."
                    ],
                )
            ],
            should_respond=True,
        )
    )


@executor(id="to_review")
async def to_review(
    _coded: AgentExecutorResponse, ctx: WorkflowContext[AgentExecutorRequest]
) -> None:
    # XL's reply is irrelevant to Amma — Amma reviews the directory on disk. So we
    # discard the coding response and emit a fresh review request.
    out_dir = Path(ctx.get_state("project_path")) / "out"
    await ctx.send_message(
        AgentExecutorRequest(
            messages=[
                Message(
                    role="system",
                    contents=[f"Review the code under directory: {out_dir}"],
                )
            ],
            should_respond=True,
        )
    )


@executor(id="to_fix")
async def to_fix(
    review: AgentExecutorResponse, ctx: WorkflowContext[AgentExecutorRequest]
) -> None:
    comments = review.agent_response.value.comments
    await ctx.send_message(
        AgentExecutorRequest(
            messages=[
                Message(
                    role="system",
                    contents=[
                        "Code review has flagged the following issues: "
                        + comments
                        + " Fix them. If needed, make sure you read existing code "
                        + "to verify correctness before writing your fixes."
                    ],
                )
            ],
            should_respond=True,
        )
    )


def review_passed(review: AgentExecutorResponse) -> bool:
    """Edge condition: stop the XL<->Amma loop when the review is done.

    NOTE — conditions receive exactly what the upstream node sent; here that is
    Amma's AgentExecutorResponse, and `.agent_response.value` is the already-parsed
    CodeReviewOutput (Amma has response_format baked in). Unlike main.py — which
    raised on a missing value and would otherwise spin forever — we treat "no
    value" as a stop, so a flaky review ends the loop instead of looping. The
    framework deliberately does NOT swallow exceptions in conditions (_edge.py), so
    keep this total and side-effect free.
    """
    verdict = review.agent_response.value
    return verdict is None or verdict.lgtm or not verdict.success


class PresentProposal(Executor):
    """Soham announces the proposal and promises the product BEFORE coding starts.

    Claude: positioned between write_proposal and xl so the "you'll have a finished
    product shortly" message lands in the same place main.py emits it (before XL
    codes), NOT after the review. It also forwards XL's coding request downstream.
    Reuses the dev session so the summary has full conversational context.
    """

    def __init__(self, dev_agent, dev_session, id: str = "present"):
        super().__init__(id=id)
        self._dev = dev_agent
        self._session = dev_session

    @handler
    async def run(
        self,
        xl_request: AgentExecutorRequest,
        ctx: WorkflowContext[AgentExecutorRequest, str],
    ) -> None:
        proposal_file_path = ctx.get_state("proposal_file_path")
        summary = await self._dev.run(
            Message(
                role="system",
                contents=[
                    "Summarize the discussion, tell the user that the proposal "
                    f"file is present at {proposal_file_path}, give him the name, "
                    "and tell him he will have a finished product shortly. DO NOT "
                    "ask any questions at this stage, as this is supposed to be the "
                    "final approach."
                ],
            ),
            session=self._session,
        )
        await ctx.yield_output(summary.text)  # emitted with executor_id="present"
        await ctx.send_message(xl_request)  # -> xl starts coding


@executor(id="done")
async def done(_review: AgentExecutorResponse) -> None:
    # Claude: terminal sink. Matching main.py, there is no extra Soham message after
    # the review — XL already reported where the code is and Amma's review was shown.
    # Receiving Amma's passing response with nothing further sent lets the run go
    # idle, which is how the driver detects completion.
    pass


def build_workflow():
    # ONE dev session, shared by the gatherer and the presenter so Soham keeps full
    # conversational memory end to end. XL and Amma get their own isolated sessions
    # (created internally by AgentExecutor).
    dev_session = sm_agent.create_session()
    gather = GatherRequirements(sm_agent, judge_agent, dev_session)
    present = PresentProposal(sm_agent, dev_session)
    xl = AgentExecutor(xl_agent, id="xl")
    amma = AgentExecutor(amma_agent, id="amma")

    # NOTE — max_iterations is the safety cap main.py's `while True` lacks, but it
    # bounds the WHOLE run (every superstep, conversation included), not just the
    # review loop. Default is 100; a very long Q&A could approach it.
    return (
        WorkflowBuilder(start_executor=gather, max_iterations=100)
        .add_edge(gather, write_proposal)
        # Soham announces the proposal (product-shortly message) BEFORE XL codes.
        .add_edge(write_proposal, present)
        .add_edge(present, xl)
        .add_edge(xl, to_review)
        .add_edge(to_review, amma)
        # Switch-case = exactly-one routing (vs. add_edge conditions, where every
        # matching edge fires). Done -> done sink; otherwise -> fix, then loop to XL.
        .add_switch_case_edge_group(
            amma,
            [Case(condition=review_passed, target=done), Default(target=to_fix)],
        )
        .add_edge(to_fix, xl)
        .build()
    )


# Claude: map executor ids -> the agent persona behind them, so outputs are
# attributed correctly. Every AgentExecutor yields its OWN response as a workflow
# output (_agent_executor.py:432), so xl and amma each surface here; without this
# map the old driver mislabeled Amma's review as "Soham".
EXECUTOR_LABELS = {"present": "Soham", "xl": "XL", "amma": "Amma"}


def _print_segment_outputs(result) -> None:
    # A WorkflowRunResult is a list of the events from THAT run() call, so printing
    # its outputs each segment surfaces messages in the order they're produced
    # (Soham's announce, then XL's code report, then Amma's review) rather than as
    # one batch at the end.
    for event in result:
        if event.type == "output":
            text = getattr(event.data, "text", None) or str(event.data)
            label = EXECUTOR_LABELS.get(event.executor_id, event.executor_id)
            print(f"\n[AGENT {label}]: {text}")


async def take_input_from_user() -> str:
    return await asyncio.to_thread(input, "\n[USER]: ")


async def answer_pending_requests(requests) -> dict:
    """Turn the workflow's pending request_info events into a responses dict.

    NOTE — two kinds of request flow through here:
      1. UserPrompt  — our own conversational asks from GatherRequirements.
      2. function-approval requests — auto-surfaced by AgentExecutor when XL calls
         write_to_file (approval_mode="always_require"). The AgentExecutor converts
         the agent's user_input_requests into workflow request_info events
         (_agent_executor.py:434-439) and resumes the agent once we answer. So the
         `always_require` approval survives the port for free — we just reuse the
         same `to_function_approval_response` call main.py used.
    """
    responses = {}
    for event in requests:
        data = event.data
        if isinstance(data, UserPrompt):
            if data.text:
                print(f"\n[AGENT Soham]: {data.text}")
            responses[event.request_id] = await take_input_from_user()
        elif hasattr(data, "to_function_approval_response"):
            print(f"\n{event.source_executor_id} needs approval:")
            print(f" Function: {data.function_call.name}")
            print(f" Arguments: {data.function_call.arguments}")
            print("Enter 'y' or 'n'.")
            approved = (await take_input_from_user()).strip().lower() == "y"
            responses[event.request_id] = data.to_function_approval_response(
                approved=approved
            )
        else:
            raise RuntimeError(f"Unexpected request payload: {type(data)!r}")
    return responses


async def main():
    workflow = build_workflow()

    # NOTE — this driver loop is the imperative shell the workflow can't absorb:
    # run -> collect pending human/approval requests -> answer -> resume. The
    # `responses=` kwarg is how you feed answers back in (_workflow.py:519). The run
    # is done when a resume returns with no more pending requests.
    result = await workflow.run("start")
    while True:
        # Surface this segment's agent outputs (labeled by source) before pausing
        # for the next human turn, so the transcript reads in chronological order.
        _print_segment_outputs(result)
        requests = result.get_request_info_events()
        if not requests:
            break
        responses = await answer_pending_requests(requests)
        result = await workflow.run(responses=responses)


if __name__ == "__main__":
    asyncio.run(main())
